[package]
name = "fragment-desktop"
version = "0.0.6"
edition.workspace = true
license.workspace = true

[lib]
name = "fragment_desktop_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
arboard.workspace = true
base64.workspace = true
fragment-core = { path = "../../../crates/fragment-core" }
image.workspace = true
serde.workspace = true
tauri = { version = "2", features = ["protocol-asset"] }
tauri-plugin-dialog = "2"
thiserror.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
url.workspace = true

[dev-dependencies]
serde_json.workspace = true
